controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
      left_wheel_names: ["rear_left_wheel_joint"]
      right_wheel_names: ["rear_right_wheel_joint"]
      publish_rate: 50.0
      base_frame_id: base_link
      use_stamped_vel: false
      wheel_separation: 0.36
      wheel_radius: 0.1
      cmd_vel_timeout: 0.5
      enable_odom_tf: true
      odom_frame_id: odom
      pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
      twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
      use_robot_state_topic: true
